// venues.js: gig venues (owned by the WORLD agent). v0.3: tier 1 (DIY) and tier 2 (bars & clubs) across the
// Saskatchewan core (cities in content/map.js). Every v0.1 venue id is kept (cards book them).
// v0.5 (CAREER agent): tier 3 theatres (500–2,000), bookable from the Signed era (economy.world.eraTier). They use
//   kind 'club' for the stage dressing until a 'theatre' kind exists; `theatre: true` marks them. The house takes its
//   cut up front, so door pay per head is lower than in the bars.
// Contract fields: id, name, city (a content/map.js city name), region, tier (1 DIY, 2 bars & clubs),
//   kind (contracts.VENUE_KINDS), capacity, minFans (fans needed to be listed/booked/offered; 99999 = card-only),
//   genreFit { metal, punk, rock, country } 0..1, quirk (one funny line), catch (the listing's small print),
//   walkIns (people there anyway), setSize (songs you play), deals (the deal options the board can list),
//   payRange { flat: [lo, hi] $ guarantee, door: [lo, hi] $ per head } (exposure always pays 0).
//   reach (v0.9, optional): road km from a band's home city within which the room books it (neighbourhood rooms).
//   deal + pay = the default deal for GG.gig.makeGig (card bookings, v0.1); gas = v0.1 round-trip $ from Saskatoon
//   (the board computes gas from road km instead).
// v0.9 "Genres": every home has starter rooms: Regina (Craig's Basement, an all-ages skate park), Edmonton + St. Albert,
//   Sherwood Park and Leduc (Alberta ring; the Mill Woods basement party is Gravel Kings' first gig), south-west
//   Saskatchewan (the Quonset yard party, halls, a rink, a rodeo, a harvest dance; Maple Creek, Gull Lake, Shaunavon).
//   Quirks and catches are tokenised ({front} {filler} {rival}) instead of naming Hail Damage. Card-only rooms per home
//   (minFans 99999, booked by the band packs' cards): city_hall_steps, westgate_parking_lot, auction_mart_stage.
(function (GG) {
  var FIT = {   // genre-fit presets: [metal, punk, rock, country]
    loud: [1, 0.9, 0.9, 0.6], diy: [0.8, 1, 0.9, 0.7], hall: [0.4, 0.5, 0.8, 1], church: [0.3, 0.4, 0.7, 0.9],
    skate: [0.9, 1, 0.8, 0.4], country: [0.3, 0.4, 0.7, 1], club: [0.9, 0.8, 1, 0.5], any: [0.8, 0.8, 0.9, 0.8]
  };
  function fit(k) { var f = FIT[k]; return { metal: f[0], punk: f[1], rock: f[2], country: f[3] }; }

  GG.content.venues = [
    /* ---- Tier 1: DIY ------------------------------------------------------------------------------ */
    { id: 'buddys_house_party', name: "Buddy's House Party", city: 'Saskatoon', region: 'canada', tier: 1, kind: 'house',
      capacity: 15, deal: 'exposure', pay: 0, minFans: 0, walkIns: 8, gas: 5, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.8, punk: 1, rock: 0.9, country: 0.7 },
      quirk: 'Twelve people and a dog.',
      catch: "Buddy's mom gets home at eleven. Hard stop." },

    { id: 'gopher_hole_openmic', name: 'The Gopher Hole — Open Mic Night', city: 'Saskatoon', region: 'canada', tier: 1, kind: 'openmic',
      capacity: 40, deal: 'exposure', pay: 0, minFans: 0, walkIns: 12, gas: 5, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.6, punk: 0.8, rock: 0.9, country: 0.9 },
      quirk: 'The host does slam poetry between acts. All of it is about his divorce.',
      catch: 'Sign-up opens at six. You go on at 11:40.' },

    { id: 'martensville_skatepark', name: 'Martensville Skatepark (All-Ages)', city: 'Martensville', region: 'canada', tier: 1, kind: 'skatepark', outdoor: true,
      capacity: 70, deal: 'exposure', pay: 0, minFans: 25, walkIns: 20, gas: 20, setSize: 3,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.9, punk: 1, rock: 0.8, country: 0.4 },
      quirk: 'The stage is a half-pipe. Nobody has ever finished a set without rolling in.',
      catch: 'Generator power. When the fries go on, the amps go off.' },

    { id: 'legion_63', name: 'Legion Hall, Branch 63', city: 'Saskatoon', region: 'canada', tier: 1, kind: 'legion',
      capacity: 60, deal: 'flat', pay: 80, minFans: 40, walkIns: 14, gas: 5, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [60, 100], door: [1, 2] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.8, country: 1 },
      quirk: 'The meat draw runs during your set, and it has the right of way.',
      catch: "Volume limit: whatever doesn't rattle the medals." },

    { id: 'bingo_palace', name: 'Bingo Palace', city: 'Saskatoon', region: 'canada', tier: 1, kind: 'bingo',
      capacity: 80, deal: 'flat', pay: 100, minFans: 70, walkIns: 25, gas: 5, setSize: 3,
      deals: ['flat'], payRange: { flat: [80, 120] },
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.8, country: 0.9 },
      quirk: 'You play between games. Every time someone yells BINGO, you stop.',
      catch: 'Dabbers are not to be thrown at the band. This is enforced loosely.' },

    { id: 'warman_curling_lounge', name: 'Warman Curling Rink Lounge', city: 'Warman', region: 'canada', tier: 1, kind: 'curling',
      capacity: 50, deal: 'flat', pay: 120, minFans: 90, walkIns: 15, gas: 25, setSize: 4,
      deals: ['flat', 'exposure'], payRange: { flat: [90, 130] },
      genreFit: { metal: 0.5, punk: 0.5, rock: 0.9, country: 1 },
      quirk: 'The window behind you overlooks sheet three. Nobody is watching you.',
      catch: 'You set up after the last end. The last end never ends.' },

    { id: 'st_vlads_hall', name: "St. Vlad's Church Hall", city: 'Saskatoon', region: 'canada', tier: 1, kind: 'church',
      capacity: 90, deal: 'flat', pay: 150, minFans: 99999, walkIns: 30, gas: 5, setSize: 4,   // card-only
      deals: ['flat'], payRange: { flat: [150, 150] },
      genreFit: { metal: 0.3, punk: 0.4, rock: 0.6, country: 0.8 },
      quirk: 'Perogies at intermission. No screaming during grace.',
      catch: 'Father Mykola approves the setlist. In advance. In writing.' },

    { id: 'craigs_basement', name: "Craig's Basement", city: 'Regina', region: 'canada', tier: 1, kind: 'house',
      capacity: 25, deal: 'exposure', pay: 0, minFans: 0, walkIns: 10, gas: 120, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.8, punk: 0.9, rock: 0.9, country: 0.7 },
      quirk: 'The ceiling is five foot eleven. {front} is six foot one, in boots.',
      catch: "Craig's roommate works nights and is asleep directly above you." },

    { id: 'leaning_silo_openmic', name: 'The Leaning Silo — Open Stage', city: 'Regina', region: 'canada', tier: 1, kind: 'openmic',
      capacity: 45, deal: 'exposure', pay: 0, minFans: 20, walkIns: 10, gas: 120, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.9, country: 1 },
      quirk: 'The stage leans four degrees west. So does the audience.',
      catch: "Every act gets a free pickle. It's not optional." },

    { id: 'speedy_creek_skate_bowl', name: 'Speedy Creek Skate Bowl', city: 'Swift Current', region: 'canada', tier: 1, kind: 'skatepark', outdoor: true,
      capacity: 60, deal: 'exposure', pay: 0, minFans: 45, walkIns: 12, gas: 122, setSize: 3,
      deals: ['exposure'], payRange: {},
      genreFit: fit('skate'),
      quirk: 'The bowl echoes. Every snare hit comes back twice, slightly late.',
      catch: 'Wind gusts to seventy. Hold on to the cymbals.' },

    // ---- v0.9: Regina's all-ages skate park, and the first rooms around the new homes ----
    // Board balance (Hail Damage baseline): the Regina skate park is a summer series (punk season) and the Quonset yard party
    // is card-only after the Ramblers' forced first gig, so a Saskatoon band's garage board is not diluted by far rooms it
    // should not play (measured: 6 years x 40 seeds, HD within noise of plan/balance_baseline_v09_hd.txt).
    { id: 'queen_city_skate_park', name: 'Queen City All-Ages Skate Park', city: 'Regina', region: 'canada', tier: 1, kind: 'skatepark', outdoor: true,
      season: ['summer'], capacity: 80, deal: 'exposure', pay: 0, minFans: 15, walkIns: 22, gas: 120, setSize: 3,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.9, punk: 0.9, rock: 0.8, country: 0.4 },
      quirk: 'Behind the rec centre. The bowl is the pit. A kid on a scooter will absolutely try to jump the kick drum.',
      catch: 'Generator power. The city shuts it off at nine sharp, mid-song or not.' },

    { id: 'mill_woods_basement_party', name: 'Mill Woods Basement Party', city: 'Edmonton', region: 'canada', tier: 1, kind: 'house',
      capacity: 20, deal: 'exposure', pay: 0, minFans: 0, walkIns: 9, gas: 265, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.8, punk: 0.9, rock: 0.8, country: 0.7 },
      quirk: 'A split-level in Mill Woods. Wood panelling, a bar made from a door and a signed hockey stick nobody can explain.',
      catch: "Somebody's parents are upstairs watching the game. Every goal, the ceiling shakes." },

    { id: 'whyte_noise_open_stage', name: 'The Whyte Noise — Open Stage', city: 'Edmonton', region: 'canada', tier: 1, kind: 'openmic',
      capacity: 45, deal: 'exposure', pay: 0, minFans: 0, walkIns: 14, gas: 265, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.6, punk: 0.8, rock: 0.7, country: 0.8 },
      quirk: 'The host plays harmonica between acts. He does not stop for the acts.',
      catch: 'Sign-up at seven. You go on after a man who only plays theremin covers.' },

    { id: 'northside_bingo_barn', name: 'Northside Bingo Barn', city: 'Edmonton', region: 'canada', tier: 1, kind: 'bingo',
      capacity: 90, deal: 'flat', pay: 100, minFans: 80, walkIns: 22, gas: 265, setSize: 3,
      deals: ['flat'], payRange: { flat: [80, 120] },
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.6, country: 0.9 },
      quirk: 'The caller has a mullet and a headset mic. He is the real rock star here.',
      catch: 'Every time someone yells BINGO, the set stops. Tuesdays are double-card nights.' },

    { id: 'st_albert_legion', name: 'St. Albert Legion, Branch 271', city: 'St. Albert', region: 'canada', tier: 1, kind: 'legion',
      capacity: 70, deal: 'flat', pay: 80, minFans: 30, walkIns: 14, gas: 270, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [60, 100], door: [1, 2] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.6, country: 1 },
      quirk: 'The dartboard is two metres from the kick drum. The darts league does not pause.',
      catch: 'Volume limit enforced by a retired sergeant with a decibel app.' },

    { id: 'earnest_bean_cafe', name: 'The Earnest Bean Folk Café', city: 'St. Albert', region: 'canada', tier: 1, kind: 'openmic',
      capacity: 35, deal: 'exposure', pay: 0, minFans: 10, walkIns: 10, gas: 270, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.2, punk: 0.4, rock: 0.4, country: 0.9 },   // the rock clash room: acoustic nights only
      quirk: 'Acoustic nights only. The sign says NO AMPLIFIERS in calligraphy. The owner reads it aloud when you walk in.',
      catch: 'The regulars snap instead of clapping. A guitar solo gets exactly one snap.' },

    { id: 'sherwood_park_curling', name: 'Sherwood Park Curling Club Lounge', city: 'Sherwood Park', region: 'canada', tier: 1, kind: 'curling',
      capacity: 55, deal: 'flat', pay: 100, minFans: 45, walkIns: 15, gas: 270, setSize: 3,
      deals: ['flat', 'exposure'], payRange: { flat: [80, 120] },
      genreFit: { metal: 0.5, punk: 0.5, rock: 0.7, country: 1 },
      quirk: 'The lounge overlooks four sheets. Every time a rock hits the house, the whole room goes "ooh".',
      catch: 'You play after the mixed league finishes. The mixed league never finishes on time.' },

    { id: 'leduc_community_hall', name: 'Leduc Oil Patch Community Hall', city: 'Leduc', region: 'canada', tier: 1, kind: 'church',
      capacity: 100, deal: 'flat', pay: 90, minFans: 55, walkIns: 20, gas: 280, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [70, 110], door: [1, 2] },
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.7, country: 0.9 },
      quirk: 'A pumpjack statue out front, a wedding social inside. You play between the speeches and the midnight lunch.',
      catch: 'The DJ gets paid more than you. The DJ has a smoke machine.' },

    { id: 'bow_river_basement', name: 'The Bow River Basement', city: 'Calgary', region: 'canada', tier: 1, kind: 'house',
      capacity: 30, deal: 'exposure', pay: 0, minFans: 20, walkIns: 12, gas: 310, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: fit('diy'),
      quirk: 'A student house near the university. Nine roommates, one bathroom, a chinook blowing through the front door.',
      catch: 'Quiet hours start at eleven. Nobody has ever observed quiet hours.' },

    { id: 'gasoline_alley_lounge', name: 'Gasoline Alley Truck Stop Lounge', city: 'Red Deer', region: 'canada', tier: 1, kind: 'bar',
      capacity: 80, deal: 'flat', pay: 90, minFans: 70, walkIns: 20, gas: 340, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [70, 110], door: [1, 2] },
      genreFit: { metal: 0.7, punk: 0.6, rock: 0.9, country: 0.9 },
      quirk: 'Between the car wash and the diesel pumps. Truckers drift in, eat pie and stay for three songs.',
      catch: 'The pie case gets the best seat in the house.' },

    { id: 'coulee_view_legion', name: 'Coulee View Legion', city: 'Lethbridge', region: 'canada', tier: 1, kind: 'legion',
      capacity: 70, deal: 'flat', pay: 90, minFans: 60, walkIns: 16, gas: 318, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [70, 110], door: [1, 2] },
      genreFit: fit('hall'),
      quirk: 'Picture windows onto the coulees and the High Level Bridge. A train crosses during every ballad.',
      catch: 'The wind holds the door shut. Load-in is a two-person job.' },

    { id: 'quonset_yard_party', name: 'Quonset Yard Party', city: 'Swift Current', region: 'canada', tier: 1, kind: 'house',
      capacity: 35, deal: 'exposure', pay: 0, minFans: 99999, walkIns: 15, gas: 122, setSize: 2,   // card-only: the Ramblers' forced first gig + C.CARD_BOOKABLE cards
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.9, country: 1 },
      quirk: 'A yard light, a bonfire, twelve pickups parked in a circle and a tailgate for a stage.',
      catch: 'Somebody always backs a truck into the fire pit. Somebody always helps.' },

    { id: 'speedy_creek_ag_hall', name: 'Speedy Creek Ag Society Hall', city: 'Swift Current', region: 'canada', tier: 1, kind: 'church',
      capacity: 100, deal: 'flat', pay: 90, minFans: 40, walkIns: 20, gas: 122, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [70, 110], door: [1, 2] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.8, country: 0.7 },
      quirk: 'Home of the fall supper, the 4-H show and, tonight, you. The stage still smells faintly of calves.',
      catch: 'The 4-H club has the hall at nine a.m. Load out tonight, or they will.' },

    { id: 'gull_lake_rink_canteen', name: 'Gull Lake Rink Canteen', city: 'Gull Lake', region: 'canada', tier: 1, kind: 'curling',
      capacity: 60, deal: 'flat', pay: 70, minFans: 20, walkIns: 18, gas: 150, setSize: 3,
      deals: ['flat', 'exposure'], payRange: { flat: [55, 90] },
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.8, country: 0.6 },
      quirk: 'You play on the canteen counter. The fries are better than the sound. The fries are very good.',
      catch: 'Minor hockey ends at eight. Forty kids in skates are your front row.' },

    { id: 'shaunavon_legion', name: 'Shaunavon Legion, Branch 88', city: 'Shaunavon', region: 'canada', tier: 1, kind: 'legion',
      capacity: 70, deal: 'flat', pay: 80, minFans: 30, walkIns: 14, gas: 160, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [60, 100], door: [1, 2] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.8, country: 0.7 },
      quirk: 'The Legion pours from the spring-water tap and brags about it. The wall of fame has a spot waiting.',
      catch: 'Bingo Wednesday, meat draw Friday, you on Saturday. Know your place in the order.' },

    { id: 'cypress_harvest_hall', name: 'Cypress Hills Harvest Dance Hall', city: 'Maple Creek', region: 'canada', tier: 1, kind: 'church',
      season: ['fall'],
      capacity: 120, deal: 'flat', pay: 110, minFans: 40, walkIns: 28, gas: 170, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [90, 140], door: [1, 2] },
      genreFit: { metal: 0.3, punk: 0.4, rock: 0.7, country: 1 },
      quirk: 'Harvest dance season: combines parked outside, a sawdust floor and lunch at midnight.',
      catch: 'The old-timers waltz to everything. Even the fast ones. Especially the fast ones.' },

    // ---- v0.9 card-only rooms (minFans 99999): the band packs' cards book them ----
    { id: 'city_hall_steps', name: 'The City Hall Steps (A Rally)', city: 'Regina', region: 'canada', tier: 1, kind: 'skatepark', outdoor: true,
      capacity: 120, deal: 'exposure', pay: 0, minFans: 99999, walkIns: 40, gas: 120, setSize: 3,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.6, punk: 1, rock: 0.8, country: 0.5 },
      quirk: 'A rally about potholes. A generator, a flatbed and a megaphone. The council chamber windows are open.',
      catch: 'A bylaw officer is timing you. So is a news crew.' },
    { id: 'westgate_parking_lot', name: 'Westgate Plaza Parking Lot Show', city: 'Edmonton', region: 'canada', tier: 1, kind: 'skatepark', outdoor: true,
      capacity: 100, deal: 'exposure', pay: 0, minFans: 99999, walkIns: 35, gas: 265, setSize: 3,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.7, punk: 0.8, rock: 1, country: 0.6 },
      quirk: 'A stage on two pallets between the nail salon and the vacuum repair. The landlord charges the crowd for parking.',
      catch: 'The vacuum repair runs a sale during your set. The vacuums are louder.' },
    { id: 'auction_mart_stage', name: 'The Auction Mart Sale Ring', city: 'Swift Current', region: 'canada', tier: 1, kind: 'church',
      capacity: 120, deal: 'flat', pay: 100, minFans: 99999, walkIns: 40, gas: 122, setSize: 3,
      deals: ['flat'], payRange: { flat: [100, 100] },
      genreFit: { metal: 0.3, punk: 0.4, rock: 0.7, country: 1 },
      quirk: 'You play in the sale ring between lots. The auctioneer sells your merch table between songs. It goes for eighty dollars.',
      catch: 'Cattle sale at nine a.m. The stage must be hosed down by then.' },

    { id: 'st_olgas_hall', name: "St. Olga's Parish Hall", city: 'Prince Albert', region: 'canada', tier: 1, kind: 'church',
      capacity: 80, deal: 'flat', pay: 80, minFans: 60, walkIns: 15, gas: 70, setSize: 3,
      deals: ['flat'], payRange: { flat: [60, 100] },
      genreFit: fit('church'),
      quirk: 'The perogy committee runs the sound board. Mostly by feel.',
      catch: "No devil horns in the hall. They'll know." },

    { id: 'legion_59_moose_jaw', name: 'Moose Jaw Legion, Branch 59', city: 'Moose Jaw', region: 'canada', tier: 1, kind: 'legion',
      capacity: 70, deal: 'flat', pay: 90, minFans: 55, walkIns: 14, gas: 110, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [70, 110], door: [1, 2] },
      genreFit: fit('hall'),
      quirk: 'A retired sergeant-major times your songs with a stopwatch.',
      catch: 'Anything over four minutes and he stands up. Nobody wants him to stand up.' },

    { id: 'battlefords_bingo_barn', name: 'Battlefords Bingo Barn', city: 'North Battleford', region: 'canada', tier: 1, kind: 'bingo',
      capacity: 90, deal: 'flat', pay: 90, minFans: 80, walkIns: 18, gas: 69, setSize: 3,
      deals: ['flat'], payRange: { flat: [70, 110] },
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.8, country: 0.9 },
      quirk: 'The barn is an actual barn. The cows were never told.',
      catch: "Play too loud and the bingo balls jump. That's a riot waiting to happen." },

    { id: 'queen_city_bingo', name: 'Queen City Bingo-Rama', city: 'Regina', region: 'canada', tier: 1, kind: 'bingo',
      capacity: 100, deal: 'flat', pay: 110, minFans: 110, walkIns: 20, gas: 120, setSize: 3,
      deals: ['flat'], payRange: { flat: [90, 130] },
      genreFit: { metal: 0.4, punk: 0.4, rock: 0.8, country: 0.9 },
      quirk: 'The caller has a louder PA than you and knows it.',
      catch: 'Intermission is the $500 blackout game. You are not the main event.' },

    { id: 'holy_pyrohy_hall', name: 'Holy Pyrohy Ukrainian Hall', city: 'Yorkton', region: 'canada', tier: 1, kind: 'church',
      capacity: 120, deal: 'flat', pay: 100, minFans: 130, walkIns: 20, gas: 165, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [80, 130], door: [1, 2] },
      genreFit: fit('church'),
      quirk: 'The dance troupe rehearses at the same time. They have swords.',
      catch: 'You play after the wedding speeches. There are eleven speeches.' },

    /* ---- Tier 2: bars & clubs (100–400) ------------------------------------------------------------ */
    { id: 'gopher_hole', name: 'The Gopher Hole', city: 'Saskatoon', region: 'canada', tier: 2, kind: 'bar',
      capacity: 150, deal: 'door', pay: 3, minFans: 150, walkIns: 20, gas: 5, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [2, 3], flat: [140, 200] },
      genreFit: { metal: 1, punk: 0.9, rock: 0.9, country: 0.6 },
      quirk: 'The sound guy hates whoever plays {instrument}. Specifically you.',
      catch: 'The monitors face the bar, not the stage. On purpose.' },

    { id: 'club_permafrost', name: 'Club Permafrost', city: 'Saskatoon', region: 'canada', tier: 2, kind: 'club',
      capacity: 300, deal: 'door', pay: 3, minFans: 800, walkIns: 40, gas: 5, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [200, 300] },
      genreFit: fit('club'),
      quirk: "The fog machine is stuck on. It's been on since the last ice age.",
      catch: "The DJ goes on at 12:30 sharp, even if you're mid-song." },

    { id: 'pile_o_bones_tavern', name: "Pile o' Bones Tavern", city: 'Regina', region: 'canada', tier: 2, kind: 'bar',
      capacity: 180, deal: 'door', pay: 2, minFans: 450, walkIns: 25, gas: 120, setSize: 4,
      deals: ['door', 'flat', 'exposure'], payRange: { door: [1.5, 2.5], flat: [150, 220] },
      genreFit: fit('loud'),
      quirk: 'The chicken wire in front of the stage is load-bearing.',
      catch: 'Load-in is through the kitchen. The cook charges a toll: one song request.' },

    { id: 'rum_runners_tunnel', name: "The Rum-Runner's Tunnel", city: 'Moose Jaw', region: 'canada', tier: 2, kind: 'bar',
      capacity: 120, deal: 'door', pay: 2, minFans: 260, walkIns: 20, gas: 110, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [120, 170] },
      genreFit: { metal: 0.8, punk: 0.9, rock: 1, country: 0.7 },
      quirk: "The ceiling is so low {front}'s hair has touched the light fixture twice. Both times during the chorus.",
      catch: 'The stage is underground. No phones work down here. Not even yours.' },

    { id: 'speedy_creek_saloon', name: 'Speedy Creek Saloon', city: 'Swift Current', region: 'canada', tier: 2, kind: 'bar',
      capacity: 140, deal: 'flat', pay: 150, minFans: 240, walkIns: 20, gas: 122, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [120, 180], door: [1.5, 2.5] },
      genreFit: fit('country'),
      quirk: "A country bar. The crowd only wants covers, and only one: 'the one about the truck'.",
      catch: 'Wrong genre pays hazard rates here. The boots are steel-toed.' },

    { id: 'gateway_bar_and_bait', name: 'Gateway Bar & Bait', city: 'Prince Albert', region: 'canada', tier: 2, kind: 'bar',
      capacity: 110, deal: 'door', pay: 2, minFans: 220, walkIns: 18, gas: 70, setSize: 4,
      deals: ['door', 'flat', 'exposure'], payRange: { door: [1.5, 2.5], flat: [110, 160] },
      genreFit: fit('any'),
      quirk: 'Half bar, half bait shop. The minnow tank sits right next to the kick drum.',
      catch: 'Part of the pay is in walleye. You may decline the walleye.' },

    { id: 'yellowhead_inn_lounge', name: 'Yellowhead Inn Lounge', city: 'North Battleford', region: 'canada', tier: 2, kind: 'bar',
      capacity: 100, deal: 'flat', pay: 130, minFans: 200, walkIns: 15, gas: 69, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [100, 150], door: [1.5, 2.5] },
      genreFit: { metal: 0.7, punk: 0.7, rock: 0.9, country: 0.9 },
      quirk: 'The VLTs are louder than the band and have a better light show.',
      catch: 'The set stops every time someone wins big. Nobody ever wins big.' },

    { id: 'grain_exchange', name: 'The Grain Exchange', city: 'Yorkton', region: 'canada', tier: 2, kind: 'club',
      capacity: 250, deal: 'door', pay: 2, minFans: 700, walkIns: 35, gas: 165, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [180, 260] },
      genreFit: { metal: 0.8, punk: 0.8, rock: 1, country: 0.8 },
      quirk: 'A converted grain elevator. Seven storeys of reverb.',
      catch: "The stage is on the third floor. The freight elevator is 'mostly fine'." },

    /* ---- Tier 3: theatres (500–2,000), from the Signed era (v0.5) ------------------------------------ */
    { id: 'broadway_bijou', name: 'The Broadway Bijou', city: 'Saskatoon', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 550, deal: 'door', pay: 1.5, minFans: 1500, walkIns: 60, gas: 5, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.2, 1.8], flat: [600, 850] },
      genreFit: { metal: 0.8, punk: 0.8, rock: 1, country: 0.8 },
      quirk: 'The velvet seats are older than your parents. {front} has asked to wear one.',
      catch: 'A seated show. The ushers shush the mosh pit.' },

    { id: 'crescent_moose_theatre', name: 'The Crescent Moose Theatre', city: 'Moose Jaw', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 500, deal: 'flat', pay: 650, minFans: 1400, walkIns: 55, gas: 110, setSize: 5,
      deals: ['flat', 'door'], payRange: { flat: [550, 800], door: [1.2, 1.8] },
      genreFit: { metal: 0.7, punk: 0.7, rock: 0.9, country: 1 },
      quirk: 'A 1916 vaudeville house. The ghost in the balcony only claps for ballads.',
      catch: 'The fly system drops a sandbag once a night. Nobody knows when.' },

    { id: 'perogy_palace_theatre', name: 'The Perogy Palace Theatre', city: 'Yorkton', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 650, deal: 'door', pay: 1.4, minFans: 2000, walkIns: 70, gas: 165, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.1, 1.7], flat: [650, 950] },
      genreFit: { metal: 0.8, punk: 0.8, rock: 0.9, country: 0.9 },
      quirk: 'The concession sells perogies by the dozen. The front row throws them during solos.',
      catch: 'Half the crowd is here for the perogies. Win them over anyway.' },

    { id: 'northern_gateway_hall', name: 'Northern Gateway Performing Arts Barn', city: 'Prince Albert', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 800, deal: 'door', pay: 1.3, minFans: 2600, walkIns: 80, gas: 70, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.0, 1.5], flat: [750, 1100] },
      genreFit: fit('any'),
      quirk: 'A real barn with real seats. The acoustics are great if you like hay.',
      catch: 'Blackflies get into the lighting rig. The lighting guy calls it "texture".' },

    { id: 'lucky_buffalo_showroom', name: 'Lucky Buffalo Casino Showroom', city: 'Regina', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 950, deal: 'flat', pay: 1000, minFans: 3200, walkIns: 110, gas: 120, setSize: 5,
      deals: ['flat', 'door'], payRange: { flat: [850, 1250], door: [0.9, 1.4] },
      genreFit: { metal: 0.5, punk: 0.5, rock: 0.9, country: 1 },
      quirk: 'The slot machines ding in 4/4, always a hair behind your tempo.',
      catch: 'Part of the pay comes in buffet vouchers. The buffet is excellent.' },

    { id: 'wascana_performing_arts', name: "Pile o' Bones Performing Arts Centre", city: 'Regina', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 1800, deal: 'door', pay: 0.9, minFans: 6500, walkIns: 150, gas: 120, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [0.7, 1.1], flat: [1300, 1800] },
      genreFit: { metal: 0.7, punk: 0.7, rock: 1, country: 0.9 },
      quirk: 'The symphony was here last night. Their timpani are still on stage, and you are not allowed to touch them.',
      catch: 'Union crew. Their lunch break is at 9:40 p.m., mid-song or not.' },

    { id: 'riverbend_auditorium', name: 'Riverbend Centennial Auditorium', city: 'Saskatoon', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 2000, deal: 'door', pay: 0.9, minFans: 8000, walkIns: 160, gas: 5, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [0.7, 1.1], flat: [1400, 1900] },
      genreFit: fit('any'),
      quirk: 'There is an orchestra pit. Someone will fall in. It is usually {filler}.',
      catch: 'Your mom bought forty tickets and will be introducing you.' },

    /* ---- v0.6.1 (Addendum 1 C6 + C7): the rest of Saskatchewan, seasonal + holiday rooms, the West, the East & North ----
       Extra fields: outdoor (weather hits turnout; off the board in winter unless a season is given), season [..] (only
       listed in these seasons), weeks [lo, hi] (only these weeks of the year), holiday (only on that holiday). Rooms in
       the West ring open in the Local Heroes era, the East & North in the Signed era (content/map.js rings). */
    { id: 'omniplex_curling_lounge', name: 'The Omniplex Curling Lounge', city: 'Humboldt', region: 'canada', tier: 1, kind: 'curling',
      capacity: 90, deal: 'flat', pay: 70, minFans: 30, walkIns: 22, gas: 226, setSize: 3,
      deals: ['flat', 'exposure'], payRange: { flat: [55, 90] },
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.9, country: 1 },
      quirk: 'The window looks onto sheet three. Every time someone yells "HURRY HARD" the crowd yells it back.',
      catch: 'You play between the draws. Twenty minutes, tops. The skips are timing you.' },

    { id: 'water_tower_polka_hall', name: 'Water Tower Polka Hall', city: 'Humboldt', region: 'canada', tier: 2, kind: 'church',
      capacity: 200, deal: 'door', pay: 2, minFans: 300, walkIns: 40, gas: 226, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [150, 220] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.8, country: 1 },
      quirk: 'The polka band before you has been together since 1971. They will critique your tempo. Kindly.',
      catch: 'At 11 p.m. the sausage comes out and nobody listens to anything. Plan your closer.' },

    { id: 'petit_salon_fransaskois', name: 'Le Petit Salon Fransaskois', city: 'Gravelbourg', region: 'canada', tier: 1, kind: 'openmic',
      capacity: 45, deal: 'exposure', pay: 0, minFans: 20, walkIns: 16, gas: 440, setSize: 2,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.9, punk: 0.8, rock: 0.8, country: 0.7 },
      quirk: 'A French-only open mic. {front} tries a song in French. The audience has follow-up questions.',
      catch: 'The host introduces every act with a ten-minute history of the cathedral.' },

    { id: 'derrick_lounge', name: 'The Derrick Lounge', city: 'Estevan', region: 'canada', tier: 2, kind: 'bar',
      capacity: 160, deal: 'flat', pay: 180, minFans: 320, walkIns: 30, gas: 440, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [150, 230], door: [1.5, 2.5] },
      genreFit: { metal: 0.9, punk: 0.7, rock: 1, country: 0.9 },
      quirk: 'The crowd works rigs. They come in coveralls, they tip in cash and they mosh like a shift change.',
      catch: 'Shift change is at eleven. Half the crowd leaves at once. Play the hit before then.' },

    // ---- v0.9: the rooms a bigger band plays around the new homes ----
    { id: 'neon_pony_saloon', name: 'The Neon Pony Saloon', city: 'Edmonton', region: 'canada', tier: 2, kind: 'bar',
      capacity: 200, deal: 'door', pay: 2, minFans: 180, walkIns: 30, gas: 265, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [150, 220] },
      genreFit: { metal: 0.8, punk: 0.8, rock: 1, country: 0.7 },
      quirk: 'Neon everywhere, a mechanical pony in the corner and a jukebox that only plays 1985.',
      catch: "The owner's cover band has Saturdays. You get Thursday. Thursday is fine." },

    // v0.9 integration (balance, plan_contract_0.9 §5 B4): Regina, Swift Current and Edmonton had too few rooms a growing band
    // can play at home, so Frost Heave and the Ramblers drove to Saskatoon for every tier-2 gig (km/gig 1.35-1.65x Hail
    // Damage). Existing cities only (no new map pins). reach: 150 = neighbourhood rooms that only book bands based within
    // 150 road km (world.inReach), so a Saskatoon band's board never sees them (Hail Damage's balance does not move).
    { id: 'cathedral_village_hall', name: 'Cathedral Village Community Hall', city: 'Regina', region: 'canada', tier: 1, kind: 'church',
      reach: 150, capacity: 80, deal: 'flat', pay: 75, minFans: 30, walkIns: 16, gas: 120, setSize: 3,
      deals: ['flat', 'exposure'], payRange: { flat: [60, 95] },
      genreFit: { metal: 0.3, punk: 0.5, rock: 0.8, country: 0.9 },
      quirk: 'Folding chairs, a bake sale and a stained-glass window of a curling rock. The squares are two for a loonie.',
      catch: 'The arts committee reads your lyrics first. Nobody on it can read {front}\'s handwriting. You are cleared.' },

    { id: 'dewdney_drop', name: 'The Dewdney Drop', city: 'Regina', region: 'canada', tier: 2, kind: 'bar',
      reach: 150, capacity: 120, deal: 'door', pay: 2, minFans: 200, walkIns: 22, gas: 120, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [110, 160] },
      genreFit: { metal: 0.5, punk: 1, rock: 0.9, country: 0.5 },
      quirk: 'A basement bar on the old avenue. The stage is an old shuffleboard table and the pucks are glued down. Mostly.',
      catch: 'The bouncer is called Moose. He is not a moose. He checks every ID twice, including the band\'s.' },

    { id: 'warehouse_district_loft', name: 'The Warehouse District Loft', city: 'Regina', region: 'canada', tier: 2, kind: 'club',
      reach: 150, capacity: 220, deal: 'door', pay: 2, minFans: 220, walkIns: 30, gas: 120, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [2, 3], flat: [170, 240] },
      genreFit: { metal: 0.5, punk: 0.9, rock: 1, country: 0.6 },
      quirk: 'The green room is a freight elevator. It goes up while you tune. It comes down when it wants.',
      catch: 'The landlord lives on the floor below and bills the promoter by the decibel.' },

    { id: 'speedy_creek_curling_lounge', name: 'Speedy Creek Curling Club Lounge', city: 'Swift Current', region: 'canada', tier: 1, kind: 'curling',
      reach: 150, capacity: 70, deal: 'flat', pay: 75, minFans: 25, walkIns: 16, gas: 122, setSize: 3,
      deals: ['flat', 'exposure'], payRange: { flat: [60, 95] },
      genreFit: { metal: 0.3, punk: 0.5, rock: 0.8, country: 0.6 },
      quirk: 'You play between draws. The skips score your songs like ends. A ballad is a blank end.',
      catch: 'Sweeping is louder than you think. The senior men sweep like it is the provincial final.' },

    { id: 'grain_elevator_cabaret', name: 'The Grain Elevator Cabaret', city: 'Swift Current', region: 'canada', tier: 2, kind: 'bar',
      reach: 150, capacity: 140, deal: 'door', pay: 2, minFans: 200, walkIns: 24, gas: 122, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [110, 160] },
      genreFit: { metal: 0.4, punk: 0.6, rock: 0.9, country: 1 },
      quirk: 'A cabaret in a retired wooden elevator. The acoustics are best described as vertical.',
      catch: 'Dust. So much dust. The fog machine is unnecessary and they run it anyway.' },

    { id: 'speedy_creek_legion', name: 'Speedy Creek Legion, Branch 56', city: 'Swift Current', region: 'canada', tier: 1, kind: 'legion',
      reach: 150, capacity: 80, deal: 'flat', pay: 80, minFans: 50, walkIns: 16, gas: 122, setSize: 3,
      deals: ['flat'], payRange: { flat: [65, 100] },
      genreFit: { metal: 0.3, punk: 0.4, rock: 0.8, country: 0.7 },
      quirk: 'Meat draw at eight, you at nine. The winner of the meat draw requests a song. It is always the same song.',
      catch: 'The Legion colour party marches through during your second set. You stop. Everyone stops.' },

    { id: 'gull_lake_hotel', name: 'Gull Lake Hotel Beverage Room', city: 'Gull Lake', region: 'canada', tier: 2, kind: 'bar',
      reach: 150, capacity: 110, deal: 'door', pay: 2, minFans: 180, walkIns: 22, gas: 150, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [100, 150] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.8, country: 1 },
      quirk: 'The beverage room has two doors: Ladies and Escorts, and Everyone Else. Both doors lead to the same bar.',
      catch: 'Last call is when the owner says so. The owner is asleep by eleven.' },

    { id: 'cypress_hills_lodge', name: 'Cypress Hills Lodge Lounge', city: 'Maple Creek', region: 'canada', tier: 2, kind: 'bar',
      reach: 150, capacity: 150, deal: 'door', pay: 2, minFans: 160, walkIns: 26, gas: 160, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [130, 190] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.8, country: 1 },
      quirk: 'Ranchers, park wardens and a bus of birdwatchers. The birdwatchers are the loudest by far.',
      catch: 'The highway to the hills closes when it snows. You may be staying the week.' },

    // v0.9 integration (balance): the home tier-1 rooms of Regina, Edmonton and south-west Saskatchewan fit punk / rock /
    // country about as well as Saskatoon's small rooms fit metal (~0.6-0.8), so every band reaches Local Heroes around the same
    // week (§5 B4: week 24 +/- 4). Metal fits are unchanged (Hail Damage's balance does not move).
    // More home rooms (v0.9 integration, reach 150): Regina, Edmonton and Swift Current get close to Saskatoon's count of
    // garage- and local-era rooms, so their bands stop driving to Saskatoon (or across Alberta) for every second gig.
    { id: 'queen_city_curling_lounge', name: 'Queen City Curling Club Lounge', city: 'Regina', region: 'canada', tier: 1, kind: 'curling',
      reach: 150, capacity: 70, deal: 'flat', pay: 70, minFans: 35, walkIns: 16, gas: 120, setSize: 3,
      deals: ['flat', 'exposure'], payRange: { flat: [55, 90] },
      genreFit: { metal: 0.3, punk: 0.4, rock: 0.8, country: 0.9 },
      quirk: 'The stage is at the hog line. Throw a good set and a skip will call it "a nice weight".',
      catch: 'The bonspiel banquet is next door. Two hundred curlers, one wall, zero patience for feedback.' },

    { id: 'plains_hotel_lounge', name: 'The Plains Hotel Lounge', city: 'Regina', region: 'canada', tier: 2, kind: 'bar',
      reach: 150, capacity: 180, deal: 'door', pay: 2, minFans: 300, walkIns: 28, gas: 120, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [150, 220] },
      genreFit: { metal: 0.5, punk: 0.9, rock: 1, country: 0.6 },
      quirk: 'A hotel bar older than the province. The carpet has seen things. The carpet will see you.',
      catch: 'The hotel guests upstairs have been promised quiet after eleven. Nobody has told the hotel guests about you.' },

    { id: 'capital_city_curling_lounge', name: 'Capital City Curling Lounge', city: 'Edmonton', region: 'canada', tier: 1, kind: 'curling',
      reach: 150, capacity: 70, deal: 'flat', pay: 70, minFans: 30, walkIns: 16, gas: 265, setSize: 3,
      deals: ['flat', 'exposure'], payRange: { flat: [55, 90] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.6, country: 0.9 },
      quirk: 'Four sheets of ice, one bar, and a scoreboard someone has changed to say ROCK ON.',
      catch: 'League night. The crowd is split between your set and a very tense tenth end.' },

    { id: 'strathcona_station_pub', name: 'The Strathcona Station Pub', city: 'Sherwood Park', region: 'canada', tier: 2, kind: 'bar',
      reach: 150, capacity: 170, deal: 'door', pay: 2, minFans: 240, walkIns: 26, gas: 270, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [130, 190] },
      genreFit: { metal: 0.6, punk: 0.7, rock: 0.9, country: 0.7 },
      quirk: 'A pub in an old train station. The last train left in 1962. The regulars are still waiting for it.',
      catch: 'The upgrader shift change empties the room at eleven. Play the loud one first.' },

    { id: 'gateway_boulevard_rock_room', name: 'The Gateway Boulevard Rock Room', city: 'Edmonton', region: 'canada', tier: 2, kind: 'club',
      reach: 150, capacity: 260, deal: 'door', pay: 2, minFans: 320, walkIns: 34, gas: 265, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [2, 3], flat: [190, 270] },
      genreFit: { metal: 0.8, punk: 0.8, rock: 1, country: 0.5 },
      quirk: 'A proper rock room: black walls, a real PA and a sound tech who says "sweet" about everything.',
      catch: 'Tuesday is the tribute-band showcase. You will be asked, more than once, who you are a tribute to.' },

    { id: 'speedy_creek_motor_inn', name: 'Speedy Creek Motor Inn Lounge', city: 'Swift Current', region: 'canada', tier: 2, kind: 'bar',
      reach: 150, capacity: 160, deal: 'door', pay: 2, minFans: 220, walkIns: 26, gas: 122, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [140, 200] },
      genreFit: { metal: 0.4, punk: 0.5, rock: 0.9, country: 1 },
      quirk: 'Truckers off the Trans-Canada, a VLT corner and a two-step crowd that knows every line of every song.',
      catch: 'The highway crews book the whole motel in spring. Some nights the lounge is just orange vests.' },

    { id: 'speedy_creek_seniors_centre', name: 'Speedy Creek Seniors\' Centre', city: 'Swift Current', region: 'canada', tier: 1, kind: 'church',
      reach: 150, capacity: 60, deal: 'flat', pay: 60, minFans: 20, walkIns: 14, gas: 122, setSize: 2,
      deals: ['flat', 'exposure'], payRange: { flat: [45, 75] },
      genreFit: { metal: 0.2, punk: 0.3, rock: 0.6, country: 0.5 },
      quirk: 'The seniors run the bar. They card you. They card everyone. They are thorough.',
      catch: 'Whist tournament at two, you at seven. The whist players will stay and critique.' },

    // The Signed-era theatres near the two homes that had none in town (tier 3; reach-limited like the rooms above).
    { id: 'speedy_creek_centennial_arena', name: 'Speedy Creek Centennial Arena', city: 'Swift Current', region: 'canada', tier: 3, kind: 'club', theatre: true,
      reach: 150, capacity: 1200, deal: 'door', pay: 0.9, minFans: 4500, walkIns: 120, gas: 122, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [0.7, 1.1], flat: [1000, 1400] },
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.9, country: 1 },
      quirk: 'The ice is under the plywood. By the encore your feet are cold and the crowd is steaming.',
      catch: 'The junior team has practice at six a.m. The Zamboni driver will be watching your load-out closely.' },

    { id: 'jubilation_auditorium', name: 'The Northern Jubilation Auditorium', city: 'Edmonton', region: 'canada', tier: 3, kind: 'club', theatre: true,
      reach: 150, capacity: 2000, deal: 'door', pay: 1, minFans: 7000, walkIns: 160, gas: 265, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [0.8, 1.2], flat: [1500, 2000] },
      genreFit: { metal: 0.7, punk: 0.7, rock: 1, country: 0.9 },
      quirk: 'Velvet seats, perfect sightlines and an usher who shushes the moshers. The moshers apologize.',
      catch: 'The ballet has the stage at noon. Every scuff mark is on your invoice.' },

    { id: 'oilcan_tavern', name: 'The Oilcan Tavern', city: 'Edmonton', region: 'canada', tier: 2, kind: 'bar',
      reach: 150, capacity: 160, deal: 'door', pay: 2, minFans: 200, walkIns: 26, gas: 265, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [120, 180] },
      genreFit: { metal: 0.6, punk: 0.8, rock: 1, country: 0.6 },
      quirk: 'Hockey on eleven TVs. You are the twelfth screen, and the only one without a power play.',
      catch: 'If the game goes to overtime, your set starts when it ends. Pray for regulation.' },

    { id: 'maple_creek_rodeo_tent', name: 'Maple Creek Rodeo Beer Tent', city: 'Maple Creek', region: 'canada', tier: 2, kind: 'bar',
      outdoor: true, season: ['summer'],
      capacity: 300, deal: 'flat', pay: 180, minFans: 120, walkIns: 40, gas: 170, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [150, 220], door: [1.5, 2.5] },
      genreFit: { metal: 0.3, punk: 0.5, rock: 0.8, country: 1 },
      quirk: 'Rodeo weekend: chuckwagons, bull riders and a beer tent with a flatbed for a stage.',
      catch: 'Wrong genre and the bull riders boo. Right genre and they buy you a round.' },

    { id: 'riverside_canada_day_stage', name: 'Riverside Park Canada Day Bandshell', city: 'Saskatoon', region: 'canada', tier: 2, kind: 'skatepark',
      outdoor: true, holiday: 'canada_day',
      capacity: 400, deal: 'exposure', pay: 0, minFans: 80, walkIns: 110, gas: 5, setSize: 4,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.7, punk: 0.8, rock: 0.9, country: 0.9 },
      quirk: 'Free show, four thousand people in red and white, a face-painting tent and a bouncy castle in the pit.',
      catch: 'No pay. The city pays in "exposure" and one hot dog each. The fireworks start mid-set.' },

    { id: 'wascana_canada_day_stage', name: 'Queen City Canada Day Lakeside Stage', city: 'Regina', region: 'canada', tier: 2, kind: 'skatepark',
      outdoor: true, holiday: 'canada_day',
      capacity: 380, deal: 'exposure', pay: 0, minFans: 100, walkIns: 100, gas: 120, setSize: 4,
      deals: ['exposure'], payRange: {},
      genreFit: { metal: 0.6, punk: 0.8, rock: 0.9, country: 1 },
      quirk: 'The stage faces the lake. The geese face the stage. The geese have the best seats.',
      catch: 'Free show. A local politician makes a speech before you. It runs long. It always runs long.' },

    { id: 'hometown_fair_grandstand', name: 'Hometown Fair Grandstand', city: 'Moose Jaw', region: 'canada', tier: 2, kind: 'skatepark',
      outdoor: true, season: ['summer'],
      capacity: 350, deal: 'flat', pay: 200, minFans: 150, walkIns: 40, gas: 110, setSize: 4,
      deals: ['flat', 'exposure'], payRange: { flat: [160, 240] },
      genreFit: { metal: 0.5, punk: 0.7, rock: 0.9, country: 1 },
      quirk: 'You play between the tractor pull and the demolition derby. The derby is louder. The derby is winning.',
      catch: 'The stage is a flatbed. It gets towed away at nine, whether you are done or not.' },

    { id: 'stampede_beer_gardens', name: 'Speedy Creek Stampede Beer Gardens', city: 'Swift Current', region: 'canada', tier: 2, kind: 'bar',
      outdoor: true, season: ['summer'],
      capacity: 300, deal: 'flat', pay: 180, minFans: 180, walkIns: 35, gas: 122, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [150, 220], door: [1.5, 2.5] },
      genreFit: { metal: 0.3, punk: 0.5, rock: 0.8, country: 1 },
      quirk: 'Rodeo week. The crowd is sunburnt, the stage is hay bales, the bull riders want the one about the truck.',
      catch: 'Wrong genre: they pay hazard rates. The boots are steel-toed AND spurred.' },

    { id: 'campus_bowl_frosh', name: 'The Campus Bowl — Frosh Week Stage', city: 'Saskatoon', region: 'canada', tier: 2, kind: 'skatepark',
      outdoor: true, weeks: [5, 6],
      capacity: 400, deal: 'flat', pay: 150, minFans: 90, walkIns: 60, gas: 5, setSize: 4,
      deals: ['flat', 'exposure'], payRange: { flat: [120, 180] },
      genreFit: { metal: 0.8, punk: 1, rock: 1, country: 0.6 },
      quirk: 'Frosh week: four hundred first-years with lanyards, face paint and no idea who you are. Yet.',
      catch: 'The student union pays by cheque. The cheque is signed by a guy named Chad and it might bounce.' },

    { id: 'harvest_dance_hall', name: 'Harvest Dance at the Rural Hall', city: 'Humboldt', region: 'canada', tier: 1, kind: 'church',
      season: ['fall'],
      capacity: 130, deal: 'flat', pay: 110, minFans: 60, walkIns: 30, gas: 226, setSize: 3,
      deals: ['flat', 'door'], payRange: { flat: [90, 140], door: [1, 2] },
      genreFit: { metal: 0.3, punk: 0.4, rock: 0.7, country: 1 },
      quirk: 'The combines are parked outside. The farmers came straight from the field. They waltz. To everything.',
      catch: 'Lunch at midnight: sandwiches, dainties and a two-hour break nobody told you about.' },

    { id: 'potash_xmas_party', name: 'Prairie Potash Co. Staff Christmas Party', city: 'Saskatoon', region: 'canada', tier: 2, kind: 'curling',
      holiday: 'christmas',
      capacity: 180, deal: 'flat', pay: 280, minFans: 150, walkIns: 60, gas: 5, setSize: 4,
      deals: ['flat'], payRange: { flat: [240, 340] },
      genreFit: { metal: 0.35, punk: 0.4, rock: 0.9, country: 0.9 },
      quirk: 'Ugly sweaters, a cash bar, a regional manager doing the worm. They booked a loud band by accident.',
      catch: 'Play "Jingle Bell Rock" or the payroll lady cries. She has done it before. It worked.' },

    { id: 'bassborough_ballroom', name: 'The Bassborough Hotel Ballroom', city: 'Saskatoon', region: 'canada', tier: 2, kind: 'club',
      weeks: [12, 12],
      capacity: 400, deal: 'flat', pay: 220, minFans: 220, walkIns: 50, gas: 5, setSize: 5,
      deals: ['flat', 'door'], payRange: { flat: [180, 260], door: [1.5, 2.5] },
      genreFit: { metal: 0.7, punk: 0.6, rock: 1, country: 0.9 },
      quirk: "A castle-looking hotel by the river, a chandelier, four hundred people in sequins. New Year's Eve only.",
      catch: 'You must count down to midnight. On time. The hotel has a clock guy and he is watching you.' },

    { id: 'paddy_ofurnitures', name: "Paddy O'Furniture's Pub", city: 'Saskatoon', region: 'canada', tier: 2, kind: 'bar',
      capacity: 170, deal: 'door', pay: 2, minFans: 200, walkIns: 30, gas: 5, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.5], flat: [140, 200] },
      genreFit: { metal: 0.8, punk: 1, rock: 0.9, country: 0.8 },
      quirk: 'An Irish pub run by a man from Estevan named Gerald. St. Paddy\'s is his Christmas. The beer is green for a week.',
      catch: 'A fiddler sits in on every set. Nobody invited him. He is very good. That is the problem.' },

    /* ---- The West (Local Heroes era) ---- */
    { id: 'frostbite_lounge', name: 'Frostbite Lounge', city: 'Winnipeg', region: 'canada', tier: 2, kind: 'club',
      capacity: 320, deal: 'door', pay: 3, minFans: 450, walkIns: 50, gas: 280, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.8, 2.8], flat: [240, 380] },
      genreFit: fit('loud'),
      quirk: 'Two blocks from the coldest corner on earth. The coat check is bigger than the stage.',
      catch: '{rival} drink here when they are in town. They will come up after and say "great set". They will mean it.' },

    { id: 'portage_main_event', name: 'The Portage & Main Event Theatre', city: 'Winnipeg', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 1400, deal: 'door', pay: 1.3, minFans: 4500, walkIns: 120, gas: 280, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [0.9, 1.4], flat: [1100, 1600] },
      genreFit: fit('any'),
      quirk: 'An old vaudeville house with a painted ceiling. The ghost in the balcony only claps for drum solos.',
      catch: 'The load-in is on the windiest street in Canada. The kick drum has blown away before.' },

    { id: 'wheat_city_wheel_inn', name: 'Wheat City Wheel Inn', city: 'Brandon', region: 'canada', tier: 2, kind: 'bar',
      capacity: 160, deal: 'flat', pay: 230, minFans: 300, walkIns: 30, gas: 340, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [190, 280], door: [1.8, 2.6] },
      genreFit: { metal: 0.8, punk: 0.8, rock: 1, country: 0.9 },
      quirk: 'Half the bar is the Winter Fair crowd, all year round. Somebody always brings a prize-winning rabbit.',
      catch: 'The stage is between the pool table and the VLTs. Mind the cues.' },

    { id: 'cowtown_saloon', name: 'Cowtown Saloon', city: 'Calgary', region: 'canada', tier: 2, kind: 'bar',
      capacity: 350, deal: 'flat', pay: 320, minFans: 500, walkIns: 60, gas: 310, setSize: 5,
      deals: ['flat', 'door'], payRange: { flat: [260, 400], door: [1.8, 2.8] },
      genreFit: fit('country'),
      quirk: 'A mechanical bull runs during your set. Someone is always on it. It is always in time.',
      catch: 'Oil money in the front row. They request the same song six times and tip a hundred each time.' },

    { id: 'saddle_sore_theatre', name: 'The Saddle Sore Theatre', city: 'Calgary', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 1600, deal: 'door', pay: 1.1, minFans: 5000, walkIns: 140, gas: 310, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [0.9, 1.4], flat: [1200, 1800] },
      genreFit: { metal: 0.8, punk: 0.7, rock: 1, country: 1 },
      quirk: 'Velvet seats, a chandelier and a hitching post outside. Somebody always parks a horse.',
      catch: 'Stampede week doubles the crowd and triples the hay on stage.' },

    { id: 'mega_mall_food_court', name: 'Mega-Mall Food Court Stage', city: 'Edmonton', region: 'canada', tier: 2, kind: 'club',
      capacity: 400, deal: 'flat', pay: 300, minFans: 550, walkIns: 120, gas: 265, setSize: 4,
      deals: ['flat', 'exposure'], payRange: { flat: [240, 360] },
      genreFit: fit('any'),
      quirk: 'Between the wave pool and the pirate ship. The crowd is holding teriyaki. The acoustics are a parking garage.',
      catch: 'Mall security enforces a strict "no moshing near the fountain" policy. There is a fountain everywhere.' },

    { id: 'oilfield_orpheum', name: 'The Oilfield Orpheum', city: 'Edmonton', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 1800, deal: 'door', pay: 1.1, minFans: 5500, walkIns: 150, gas: 265, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [0.9, 1.3], flat: [1300, 1900] },
      genreFit: fit('loud'),
      quirk: 'A 1920s theatre with a pipe organ. The organist offers to sit in. Say yes. Trust us.',
      catch: 'The Festival City crowd has seen everything. Show them something they have not.' },

    { id: 'deer_crossing_tavern', name: 'The Deer Crossing Tavern', city: 'Red Deer', region: 'canada', tier: 2, kind: 'bar',
      capacity: 200, deal: 'door', pay: 2.2, minFans: 350, walkIns: 35, gas: 340, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.8, 2.6], flat: [200, 300] },
      genreFit: { metal: 0.9, punk: 0.8, rock: 1, country: 0.9 },
      quirk: 'Exactly halfway between Calgary and Edmonton. Both cities\' bands stop here. Nobody stays.',
      catch: 'A taxidermied deer watches from above the stage. Its name is Gary. Gary judges.' },

    { id: 'chinook_lounge', name: 'The Chinook Lounge', city: 'Lethbridge', region: 'canada', tier: 2, kind: 'bar',
      capacity: 180, deal: 'flat', pay: 240, minFans: 320, walkIns: 30, gas: 318, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [200, 300], door: [1.8, 2.6] },
      genreFit: { metal: 0.8, punk: 0.9, rock: 0.9, country: 0.9 },
      quirk: 'The wind blows the door open every nine minutes. The crowd leans into it out of habit.',
      catch: 'A warm chinook wind turns the parking lot into a lake by midnight. Bring boots.' },

    { id: 'ogopogo_pub', name: "Ogopogo's Pub", city: 'Kelowna', region: 'canada', tier: 2, kind: 'bar',
      capacity: 220, deal: 'door', pay: 2.4, minFans: 600, walkIns: 45, gas: 610, setSize: 4,
      deals: ['door', 'flat'], payRange: { door: [1.8, 2.8], flat: [280, 420] },
      genreFit: { metal: 0.7, punk: 0.8, rock: 1, country: 0.9 },
      quirk: 'Lakeside, with a patio full of wine tourists. They clap politely, then buy all the merch.',
      catch: 'The owner swears the lake monster comes to shows. There is a reserved table. It is always empty.' },

    { id: 'rainy_day_room', name: 'The Rainy Day Room', city: 'Vancouver', region: 'canada', tier: 2, kind: 'club',
      capacity: 300, deal: 'door', pay: 2.6, minFans: 800, walkIns: 60, gas: 900, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [2, 3.2], flat: [380, 560] },
      genreFit: fit('club'),
      quirk: 'Everybody arrives soaked. The coat rack is just a pile. The vibe is excellent.',
      catch: 'Rent is so high the venue shares the stage with a yoga studio. Load out before the 7 a.m. class.' },

    { id: 'commandant_ballroom', name: 'Commandant Ballroom', city: 'Vancouver', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 990, deal: 'door', pay: 1.5, minFans: 6000, walkIns: 100, gas: 900, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.2, 1.8], flat: [1400, 2100] },
      genreFit: fit('club'),
      quirk: 'A legendary sprung dance floor. When the crowd jumps, the whole room bounces. So does the drum riser.',
      catch: 'Everyone who ever mattered played here. Their photos are on the wall. They are all watching you.' },

    { id: 'emptress_tea_room', name: 'The Emptress Tea Room (After Dark)', city: 'Victoria', region: 'canada', tier: 2, kind: 'club',
      capacity: 150, deal: 'flat', pay: 320, minFans: 700, walkIns: 25, gas: 960, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [280, 420], door: [2, 3] },
      genreFit: { metal: 0.5, punk: 0.6, rock: 0.9, country: 0.8 },
      quirk: 'High tea until nine, then loud music until one. The scones stay out. {front} eats eleven.',
      catch: 'The last ferry back leaves at 11. You will miss it. Everyone misses it.' },

    /* ---- The East & North (Signed era) ---- */
    { id: 'sleeping_giant_saloon', name: 'Sleeping Giant Saloon', city: 'Thunder Bay', region: 'canada', tier: 2, kind: 'bar',
      capacity: 220, deal: 'flat', pay: 520, minFans: 1500, walkIns: 40, gas: 980, setSize: 5,
      deals: ['flat', 'door'], payRange: { flat: [450, 650], door: [2.5, 3.5] },
      genreFit: fit('loud'),
      quirk: 'Halfway across the country and the crowd acts like it. Nobody here has seen a band in a month. They are STARVING.',
      catch: 'The drive here is the tour. The Trans-Canada, one lane each way, for eleven hours.' },

    { id: 'the_hoofprint', name: 'The Hoofprint', city: 'Toronto', region: 'canada', tier: 2, kind: 'bar',
      capacity: 400, deal: 'door', pay: 4, minFans: 2500, walkIns: 80, gas: 1400, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [3, 4.5], flat: [700, 1000] },
      genreFit: fit('club'),
      quirk: 'A legendary tavern with a horseshoe-shaped bar and seventy years of sweat in the floorboards.',
      catch: 'Toronto crowds stand with their arms crossed. That is applause here. You will have to trust it.' },

    { id: 'messy_hall', name: 'Messy Hall', city: 'Toronto', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 2000, deal: 'door', pay: 1.8, minFans: 12000, walkIns: 200, gas: 1400, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.5, 2.3], flat: [3000, 4200] },
      genreFit: fit('any'),
      quirk: 'The most famous room in the country. The ceiling is a century old. The acoustics make your {instrument} sound like thunder.',
      catch: 'Your mom flew in. She is in the royal box. She brought a sign. The sign says your childhood nickname.' },

    { id: 'question_period_pub', name: 'Question Period Pub', city: 'Ottawa', region: 'canada', tier: 2, kind: 'bar',
      capacity: 260, deal: 'flat', pay: 650, minFans: 2000, walkIns: 50, gas: 1300, setSize: 5,
      deals: ['flat', 'door'], payRange: { flat: [550, 800], door: [2.5, 4] },
      genreFit: { metal: 0.7, punk: 0.9, rock: 1, country: 0.8 },
      quirk: 'Staffers from the Hill. They heckle in both official languages and demand a point of order mid-solo.',
      catch: 'Every request needs unanimous consent. You will not get unanimous consent.' },

    { id: 'club_poutine_sonore', name: 'Club Poutine Sonore', city: 'Montréal', region: 'canada', tier: 2, kind: 'club',
      capacity: 350, deal: 'door', pay: 4, minFans: 2200, walkIns: 70, gas: 1500, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [3, 4.5], flat: [650, 950] },
      genreFit: fit('loud'),
      quirk: 'The loudest metal crowd in the country. They sing the guitar riffs. In French. In harmony.',
      catch: '{front} announces every song in French. The crowd corrects the grammar. Lovingly.' },

    { id: 'le_megalopolis', name: 'Le Mégalopolis', city: 'Montréal', region: 'canada', tier: 3, kind: 'club', theatre: true,
      capacity: 1900, deal: 'door', pay: 1.7, minFans: 10000, walkIns: 180, gas: 1500, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [1.4, 2.1], flat: [2800, 3900] },
      genreFit: fit('loud'),
      quirk: 'A grand old music hall. The mosh pit here has its own traditions, rules and a union rep.',
      catch: 'The crowd will not let you leave. Plan three encores. Then a fourth.' },

    { id: 'bonhomme_bar', name: 'Le Bonhomme Bar', city: 'Québec City', region: 'canada', tier: 2, kind: 'bar',
      capacity: 240, deal: 'flat', pay: 600, minFans: 1800, walkIns: 50, gas: 1640, setSize: 5,
      deals: ['flat', 'door'], payRange: { flat: [520, 760], door: [2.5, 4] },
      genreFit: { metal: 0.9, punk: 0.8, rock: 1, country: 0.7 },
      quirk: 'Inside the old city walls. A man in a snowman costume dances in the front row. He is always here.',
      catch: 'Winter Carnival crowds bring a cane full of something warm. You will be offered some. Pace yourself.' },

    { id: 'lobster_trap_kitchen_party', name: 'Lobster Trap Kitchen Party', city: 'Halifax', region: 'canada', tier: 2, kind: 'bar',
      capacity: 260, deal: 'door', pay: 3.5, minFans: 2000, walkIns: 60, gas: 2000, setSize: 5,
      deals: ['door', 'flat'], payRange: { door: [2.5, 4], flat: [600, 850] },
      genreFit: { metal: 0.7, punk: 0.9, rock: 1, country: 1 },
      quirk: 'Every set turns into a kitchen party. Someone brings a fiddle. Someone brings spoons. Someone brings a lobster.',
      catch: 'The noon gun goes off every day at twelve. You play at night. Your stage brain will still flinch.' },

    { id: 'screech_in_room', name: 'The Screech-In Room', city: "St. John's", region: 'canada', tier: 2, kind: 'bar',
      capacity: 200, deal: 'flat', pay: 700, minFans: 2400, walkIns: 55, gas: 2500, setSize: 5,
      deals: ['flat', 'door'], payRange: { flat: [600, 850], door: [3, 4.5] },
      genreFit: { metal: 0.8, punk: 1, rock: 1, country: 0.9 },
      quirk: 'After the set you get screeched in: a shot, a rhyme and a cod to kiss. The cod is non-negotiable.',
      catch: 'The fog is so thick the load-in is by feel. {front} walked into the harbour once. Everyone is fine.' },

    { id: 'sourtoe_saloon', name: 'The Sourtoe Saloon', city: 'Whitehorse', region: 'canada', tier: 2, kind: 'legion',
      capacity: 140, deal: 'flat', pay: 750, minFans: 1600, walkIns: 45, gas: 1850, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [650, 900], door: [3, 4] },
      genreFit: { metal: 0.9, punk: 0.9, rock: 1, country: 1 },
      quirk: 'A Gold Rush hall with a famous cocktail. There is a toe in it. A real one. {filler} wants to try.',
      catch: 'In June the sun never sets. You will play at 1 a.m. in broad daylight and it will break your brain.' },

    { id: 'ice_road_tavern', name: 'The Ice Road Tavern', city: 'Yellowknife', region: 'canada', tier: 2, kind: 'bar',
      capacity: 160, deal: 'flat', pay: 800, minFans: 1700, walkIns: 50, gas: 1600, setSize: 4,
      deals: ['flat', 'door'], payRange: { flat: [700, 950], door: [3, 4.5] },
      genreFit: fit('loud'),
      quirk: 'The truckers who drive the ice roads drink here. They mosh like men who have seen things.',
      catch: 'The northern lights come out mid-set. The whole crowd walks outside to look. Wait for them.' }
  ];

  // Local bands you can open for (opening slots on the board). draw = the crowd they bring on their own.
  // The rival (bands[..].rival) can headline too, rarely; its draw is in 26_sim_world's config.
  GG.content.headliners = [
    { id: 'combine_of_sorrow', name: 'Combine Harvester of Sorrow', city: 'Saskatoon', genre: 'metal', draw: 120,
      blurb: 'Doom metal about crop insurance. Every song is eleven minutes long.' },
    { id: 'slough_monster', name: 'Slough Monster', city: 'Regina', genre: 'metal', draw: 100,
      blurb: 'Swamp sludge from the flattest place on earth. They bring their own fog, and it smells.' },
    { id: 'the_hoarfrosts', name: 'The Hoarfrosts', city: 'Saskatoon', genre: 'punk', draw: 90,
      blurb: 'Three chords, one parka each. They only play in winter, out of principle.' },
    { id: 'rm_344', name: 'Rural Municipality 344', city: 'Moose Jaw', genre: 'punk', draw: 80,
      blurb: 'Angry songs about gravel road maintenance. The reeve is a fan.' },
    { id: 'bunnock_kings', name: 'The Bunnock Kings', city: 'Regina', genre: 'rock', draw: 140,
      blurb: 'Bar rock named after a lawn game played with horse bones. Every show ends in a tournament.' },
    { id: 'gopher_derby', name: 'The Gopher Derby', city: 'Prince Albert', genre: 'rock', draw: 90,
      blurb: 'Garage rock with a mascot costume. Nobody knows who is inside the gopher.' },
    { id: 'stubble_burners', name: 'Stubble Burners', city: 'Swift Current', genre: 'country', draw: 130,
      blurb: 'Two brothers, one fiddle, a combined forty belt buckles.' }
  ];
})(window.GG);
